[package]
name = "sitemap-rs"
version = "0.1.0"
edition = "2021"
rust-version = "1.63"
authors = ["Todd Everett Griffin <toddgriffin@protonmail.com>"]
readme = "README.md"
repository = "https://github.com/goddtriffin/sitemap-rs"
homepage = "https://www.toddgriffin.me/"
description = "Library to generate URL, Index, Image, Video, News sitemaps."
license-file = "LICENSE.txt"
keywords = ["sitemap", "sitemapindex", "urlset", "url", "image:image", "video:video", "news:news"]
categories = ["web-programming", "parsing"]

[dependencies]
xml-builder = "0.5.0"
chrono = "0.4.22"
