[package]
name = "sitemap-rs"
version = "0.1.1"
edition = "2021"
rust-version = "1.63"
authors = ["Todd Everett Griffin <toddgriffin@protonmail.com>"]
repository = "https://github.com/goddtriffin/sitemap-rs"
homepage = "https://www.toddgriffin.me/"
description = "A Rust library to generate URL, Index, Image, Video, and News sitemaps."
license = "MIT"
keywords = ["sitemap", "index-sitemap", "image-sitemap", "video-sitemap", "news-sitemap"]
categories = ["web-programming", "parsing"]
exclude = [
    ".idea/*",
    ".github/*",
]

[dependencies]
xml-builder = "0.5.0"
chrono = "0.4.22"
